### ISSUE TITLE
"(node:6924) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unauthorized"

### ISSUE THREAD

**Issue by AheadBL** [Woofie-Woof/Yoshi-Bot#3] opened 2017-01-04 00:32 UTC
I'm starting the bot, but when I say a command or delete a message, i'm told about an Unhandled promise rejection, saying "Unauthorized", then the bot crashes for "Unexpected end of JSON input".

Full logs:
C:\Users\Etienne\ee>node YoshiBot.js
New and rehauled Yoshi-Bot online and ready to serve!
*This is where I deleted a message.*
(node:6924) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: Unauthorized
(node:6924) DeprecationWarning: Unhandled promise rejections are deprecated. In
the future, promise rejections that are not handled will terminate the Node.js p
rocess with a non-zero exit code.
undefined:1

*This is when I triggered a command. Yes, the commands.js file exists.*
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Client.<anonymous> (C:\Users\Etienne\ee\YoshiBot.js:97:28)
    at emitOne (events.js:101:20)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (C:\Users\Etienne\ee\node_modules\discord.js\
src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Etienne\ee\node_modules\discord.j
s\src\client\websocket\packets\WebSocketPacketManager.js:93:65)
    at WebSocketManager.eventMessage (C:\Users\Etienne\ee\node_modules\discord.j
s\src\client\websocket\WebSocketManager.js:198:31)
    at WebSocket.ws.onmessage (C:\Users\Etienne\ee\node_modules\discord.js\src\c
lient\websocket\WebSocketManager.js:74:37)
    at WebSocket.onMessage (C:\Users\Etienne\ee\node_modules\ws\lib\WebSocket.js
:442:14)
    at emitTwo (events.js:106:13)

Any help would be appreciated.

**Comment by MarioGraceZ22** [comment] 2017-01-04 04:12
Hello. I forgot to include this in the bot's files, but do you have, per chance, a folder in the bot's folders named "data" with the files "servers.json" and "info.json"? The fiile structure should look something like the attached images.

![explorer_2017-01-03_21-09-58](https://cloud.githubusercontent.com/assets/12266438/21631489/0c74be12-d1f9-11e6-9775-76512443002d.png)
![explorer_2017-01-03_21-10-13](https://cloud.githubusercontent.com/assets/12266438/21631490/0f680390-d1f9-11e6-93ea-8d6897072930.png)

Aside from that, which Node.js version are you using? Do you have all the dependencies? As of now, I'm not exactly sure what the source of the bug is, but you say it happens as soon as you use a command or delete a message, right? Did you check to see if it also happened by just plain sending a message?

**Comment by AheadBL** [comment] 2017-01-29 22:35
Sorry about the long wait; I didn't notice you replied.

Anyways, another issue: I downgraded to Discord.JS 9.1.0, and when I DM my bot anything...

`C:\Users\Etienne\Desktop\Yoshi-Bot-master\yoshibot.js:144
    if(!serversInfo[msg.guild.id]){
                             ^
TypeError: Cannot read property 'id' of null
    at Client.<anonymous> (C:\Users\Etienne\Desktop\Yoshi-Bot-master\yoshibot.js
:144:30)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (C:\Users\Etienne\Desktop\Yoshi-Bot-master\no
de_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:3
4)
    at WebSocketPacketManager.handle (C:\Users\Etienne\Desktop\Yoshi-Bot-master\
node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:9
3:65)
    at WebSocketManager.eventMessage (C:\Users\Etienne\Desktop\Yoshi-Bot-master\
node_modules\discord.js\src\client\websocket\WebSocketManager.js:182:31)
    at WebSocket.ws.onmessage (C:\Users\Etienne\Desktop\Yoshi-Bot-master\node_mo
dules\discord.js\src\client\websocket\WebSocketManager.js:65:37)
    at WebSocket.onMessage (C:\Users\Etienne\Desktop\Yoshi-Bot-master\node_modul
es\ws\lib\WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)`

Aside from that, the same issue with the Error: Unauthorized stuff is still happening.

[Here's the full log if you need it.](https://puu.sh/tFUqq/8ac81000de.txt)

**Comment by Woofie-Woof** [comment] 2017-01-30 16:58
I did think you'd only need to update Node.js to fix the other issue. Seems like something caused by the newer Discord.js versions (make sure you're using the latest of Discord.js, now).

The DM bug is something I caused with a recent update that handles server settings and whatnot. I'll try to roll out a fix tonight. Thanks for pointing it out!

**Comment by Woofie-Woof** [comment] 2017-01-31 07:51
The latest [commit](https://github.com/Woofie-Woof/Yoshi-Bot/commit/5bf21849b798a45cbd0d42fda8c1b00ae16c73a3) to my repository should fix the issue with DMs. If you run into anything else, please let me know. I'll close this issue for now.

**Closed by Woofie-Woof** 2017-01-31 07:51 UTC
Labels: bug, help wanted
